name: AniList readme workflow
on:
    schedule:
        # Runs every hour
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    update-readme-with-anilist:
        name: \`Updated\` this repo's README with latest AniList activites
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: AniList readme workflow
              uses: pxseu/anilist-readme@v1.4.2

              with:
                  user_id: 6088410
                  max_post_count: 5
                  timezone: "Asia/Jakarta"
                  date_format: "{h}:{m} // {D} {MW}, {Y}"
