name: Metrics
on:
  schedule:
    - cron: "0 0-22/2 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Personal metrics (anilist)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.personal.anilist.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: watching, favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_shuffle: yes
          plugin_anilist_limit_characters: 22
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
